# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
   name: selfLinuxagent
   demands: 
    - agent.name -equals myLinuxVM

stages:
- stage: Build
  jobs:
    - job: Fristjob
      steps:
        - bash: echo build firstjob
    - job: secondjob
      steps:
        - bash: echo build second job
        - bash: echo $(PipelineLevelVariable) 
        
- stage: Devdeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
     - job: Devdeployjob
       steps:
         - bash: echo $(environment) job
- stage: QAdeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
    - job: QAdeplojob
      steps:
        - bash: echo $(environment) job
- stage: proddeploy
  variables:
    environment: prod
  dependsOn: 
  - Devdeploy
  - QAdeploy
  jobs:
    - job: proddeployjob
      steps:
       - bash: echo $(environment) job    



