# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
   name: selfLinuxagent
   demands: 
    - agent.name -equals myLinuxVM

stages:
- stage: Build
  jobs:
    - job: Fristjob
      steps:
        - bash: echo build firstjob
    - job: secondjob
      steps:
        - bash: echo build second job
- stage: Devdeploy
  jobs:
     - job: Devdeployjob
       steps:
         - bash: echo Devdeploy job
- stage: QAdeploy
  jobs:
    - job: QAdeplojob
      steps:
        - bash: echo QAdeploy job
- stage: proddeploy
  jobs:
    - job: proddeployjob
      steps:
       - bash: echo proddeploy job    



